### ISSUE TITLE
Small name changes

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/characters#21]
1. `iteratorAtEnd` is really confusing. It should be called `reverseIterator` or `iteratorReversed`.

2. A lot of methods have their parameters called `other`. I would prefer to call them `sequence`. For example: `bool startsWith(Characters sequence)` instead of `bool startsWith(Characters other)`

Of course, this is a matter of taste, so feel free to disagree.

**Comment by lrhn** [comment]
The `iteratorAtEnd` is not a reversed iterator. You don't use `moveNext` to move backwards like I'd expect for a reversed iterator.
It's just an iterator which is currently at the end, just as if you had done `var it = chars.iterator; while(chars.moveNext());`.
So, the name is precise.

Not sure what `sequence` would add. It's a *new* concept (we use "sequence of characters" to say what a `Characters` object represents, and occasionally use it implicitly about the sequence of characters of a `Characters` object, but we don't "sequence" as a stand-alone noun).
If anything, I'd use `characters` instead of `other`. That would actually be better.

**Comment by marcglasberg** [comment]
Ok, at the time I wrote this I didn't understand that `Characters.iterator` is not a traditional iterator, and can move both directions. I'm not sure but I believe this fact was not clear in the docs at the time.

I agree with `bool startsWith(Characters characters)`
