### ISSUE TITLE
Support for ANSI characters

### ISSUE THREAD

**Issue by knaeckeKami** [dart-lang/characters#39]
consider this example

```dart
import 'package:characters/src/characters.dart';


const ansiEscape = '\x1B[';

/// Reset all colors and options for current SGRs to terminal defaults.
const ansiDefault = '${ansiEscape}0m';

const greenXterm = '2';

String green(String orig) =>
    '${ansiEscape}38;5;${greenXterm}m$orig$ansiDefault';


void main(){

  final greenString = green('test');

  print("$greenString has a characters length of ${Characters(greenString).length}");



}
```

this prints this `test has a characters length of 17` (see [image](https://imgur.com/a/D8JVWRi) ) on a terminal with ANSI-support.

I wonder if it's feasible to get the real user-perceived character count of 4 here.

**Comment by lrhn** [comment]
That would not be the count of *Unicode* grapheme clusters. The string `"\x1b[0m;` contains five Unicode code points and five Unicode grapheme clusters. Some of them might end up being invisible when printed because the target has further interpretation of the bytes, but I am not aware of any intersection between ANSI escape sequences and Unicode (do enlighten me if I've missed it).

So, I'd prefer to not go into that can of worms, also because I'm sure there are lots of other possible byte interpretations that we would also be asked to consider. 

I recommend removing escape sequences first, or perhaps splitting the string/characters into visible and control parts afterwards.

**Comment by knaeckeKami** [comment]
Yeah, stripping out ANSI before works for me.
