### ISSUE TITLE
Zero-Width Non-Joiner (\u200c) character does not count

### ISSUE THREAD

**Issue by Pourqavam** [dart-lang/characters#61]
Hi
Some languages like Persian uses `\u200c` (Zero-Width Non-Joiner) as half space (Shift + Space), but this package does not count this character. It makes problem in max length of the Flutter text field (native Android counts it properly).
```dart
// Zero-Width Non-Joiner (invisible character)
print(Characters('س\u200cس').length); // Prints 2 (Incorrect)

// Left-to-Right Mark (invisible character)
print(Characters('س\u200eس').length); // Prints 3 (Correct)
```
https://en.wikipedia.org/wiki/Zero-width_non-joiner

**Comment by lrhn** [comment]
This package is not locale aware, and does not have access to platform Unicode support (if any is available).

As such, it treats ZWNJ as its default category:

><pre>200C ; Extend # Cf ZERO WIDTH NON-JOINER</pre>

Being "Extend" means it combines with the previous character in most cases (not control characters or other special exceptions). That makes a kind of sense (to me), since it's a non-rendering marker which prevents two other characters from being joined. If successful, the original two characters should count as two characters, and the, otherwise irrelevant, separator hides in the former grapheme cluster without affecting rendering of it. There will be two glyphs rendered, so having a length of 2 makes sense.

Whether it's *correct* is another question, and it probably isn't for all locales or scripts, but sadly this package doesn't know about that.
The implementation here blindly follows the extended grapheme cluster breaking algorithm using the default breaking category of each code point, which for the ZWNJ means being an "extend" character.

I'll close with "cannot fix".
